title: jekyll-rtd-theme
description: Just another documentation theme compatible with GitHub Pages

theme: null

title                    : "Test - jeothen.github.io"
name                     : "jeothen"
description              : "학습한 내용을 정리하는 공간"
url: https://jeothen.github.io
baseurl: ""
      
# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
